### PR TITLE
6.0.0 dev bmi 1

### PR DESCRIPTION
**Pull request by rmcd-mscb**
Hey Mark,
I committed changes I made to my forked repo branch of 6.0.0_bmi_dev -> 6.0.0_bmi_dev_1.  I'll leave this as a pull request until your ready with your changes.

### CODE REVIEW

**Comment by mdpiper** [comment]
@rmcd-mscb I'm rebasing my `try-pointers` branch on this one. There are a few conflicts, but it looks like they'll be easy to fix. I'll get back to you soon.

**Comment by rmcd-mscb** [comment]
Thanks Mark!
________________________________

**Review by mdpiper — APPROVED** [review]

**Comment by mdpiper** [comment]
@rmcd-mscb Please merge this branch whenever you wish. I'll prepare a PR with my PRMS changes afterward. Thanks, Rich!

**Comment by rmcd-mscb** [comment]
Thanks Mark!

**Pull request merged**
