### PR TITLE
Allow by-reference access to type components

### PR DESCRIPTION
**Pull request by mdpiper**
PRMS is an OO program, with model variables defined as components of a series of derived types. For tight coupling in an interoperable framework, it's important to be able to access these type components by reference, so that large data arrays aren't copied between coupled components. This implies the use of the `c_loc` function to obtain a C pointer reference for a Fortran variable. The `c_loc` function requires the `target` or `pointer` attribute to be set on a variable. Type components can't use `target`, but they can use `pointer`. This PR is an exploration of using pointers instead of allocatable variables in PRMS.

In this PR, I've changed type components with the `allocatable` attribute to `pointer`. I tried to minimize the changes by only modifying type components, and of those, only ones that weren't marked private or local. I also didn't modify the top-level Simulation class or character arrays. Everything appears to work (although we really need tests). PRMS compiles. When I run the pipestem example with the default control file, the netCDF output file **summary_daily.nc** is a bitwise match to the same file created without the changes in this PR.

### CODE REVIEW

**Comment by mdpiper** [comment]
@rmcd-mscb Hang on -- there's some weirdness. I think I'll need one more commit to fix it.

**Comment by mdpiper** [comment]
@rmcd-mscb OK, fixed. All clear!

**Review by rmcd-mscb — APPROVED** [review]
Looks good Mark,  There maybe just a couple more to change.  I blew my previous pull request.  I should have merged 6.0.0_dev_bmi_1 into 6.0.0_dev_bmi, not 6.0.0_bmi_dev (careful here!) as I did.  However, I was able to simply merge 6.0.0_bmi_dev back into 6.0.0_dev_bmi.  

I'm pretty sure there will be about 10 more vars that I changed from private to not, that may need these same changes.  

Sorry about that confusion!  Once we get it all merged back we can delete 6.0.0_bmi_dev!!  Let me know if you have any questions about this

**Comment by mdpiper** [comment]
@rmcd-mscb Oh, I see. I've frequently confused these two branches, and I did it here again. I'll merge this PR so you can rebalance the branches.

**Pull request merged**
